# force run: 41
language: python
python:
  - "2.7"
#  - "3.3"
#  - "3.4"
#  - "3.5"
  - "3.6"
before_install:
  - echo "+++ hosts orig +++"
  - cat /etc/hosts
  - echo "--- hosts orig ---"
  - sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'
  - sudo sh -c 'echo >> /etc/hosts; grep "^127.0.0.1" /etc/hosts | sed "s|^127.0.0.1|::1|g" >> /etc/hosts'
  - echo "+++ hosts patched +++"
  - cat /etc/hosts
  - echo "--- hosts patched ---"
  - sudo -H DEBIAN_FRONTEND=noninteractive apt-get update
  - sudo -H DEBIAN_FRONTEND=noninteractive apt-get install gpp
  - sh -x ./install_depends/opensips.sh
script:
    sh -x ./test_run.sh
env:
## 2. Tests with OpenSIPS
  - MM_TYPE=opensips MM_BRANCH=master MM_REV=fbecd4397a26b28dfee5eec283de17214c178eaf RTPP_BRANCH=master RTPPC_TYPE=udp
  - MM_TYPE=opensips MM_BRANCH=master MM_REV=1f821b1ac864eda75b06675ecc3b7af63f4d56c8 RTPP_BRANCH=master RTPPC_TYPE=udp
  - MM_TYPE=opensips MM_BRANCH=master MM_REV=d2f780cb8be6eef5d9cccd219e5516a9792aae69 RTPP_BRANCH=master RTPPC_TYPE=udp
  - MM_TYPE=opensips MM_BRANCH=master MM_REV=9349a061a2bc21991ddbdb7db5b1fbdaaf18c528 RTPP_BRANCH=master RTPPC_TYPE=udp
  - MM_TYPE=opensips MM_BRANCH=master MM_REV=8b054a173f678541f1066e96c3d44b4e2027c158 RTPP_BRANCH=master RTPPC_TYPE=udp
  - MM_TYPE=opensips MM_BRANCH=master MM_REV=243fcee7abbfeb7595a77263d9b8fa8a8bde259b RTPP_BRANCH=master RTPPC_TYPE=udp
  - MM_TYPE=opensips MM_BRANCH=master MM_REV=572f0df73ea9f70ee9fcb85206312a9be25c7a00 RTPP_BRANCH=master RTPPC_TYPE=udp
  - MM_TYPE=opensips MM_BRANCH=master MM_REV=4adb1bb5035b422de95dbf587890b9b75efb61ba RTPP_BRANCH=master RTPPC_TYPE=udp
  - MM_TYPE=opensips MM_BRANCH=master MM_REV=c7d02c0a7e1e29d05b635ea6e0981bfb87330fa3 RTPP_BRANCH=master RTPPC_TYPE=udp
  - MM_TYPE=opensips MM_BRANCH=master MM_REV=41ad6727f3d7a17370c38db5d06f0dcdf450b30b RTPP_BRANCH=master RTPPC_TYPE=udp
  - MM_TYPE=opensips MM_BRANCH=master MM_REV=a6a0d812fb5a506324e363e88cd39167e66abe45 RTPP_BRANCH=master RTPPC_TYPE=udp
  - MM_TYPE=opensips MM_BRANCH=master MM_REV=6d7b8ec714edb9b7e25345754ea4ba41f8b566dd RTPP_BRANCH=master RTPPC_TYPE=udp
  - MM_TYPE=opensips MM_BRANCH=master MM_REV=23fea2f8c8d6f6811abebd34c3efdadb3c6e49ec RTPP_BRANCH=master RTPPC_TYPE=udp
  - MM_TYPE=opensips MM_BRANCH=master MM_REV=c202cfc2a4f0f663cee0585d7bbb687e7fe42b3d RTPP_BRANCH=master RTPPC_TYPE=udp
  - MM_TYPE=opensips MM_BRANCH=master MM_REV=7a1cf1d923de9f2dbb9d1b5dce1586eaecceae98 RTPP_BRANCH=master RTPPC_TYPE=udp
  - MM_TYPE=opensips MM_BRANCH=master MM_REV=a58f76c0df6645a9a4fd44144e155becebfd03af RTPP_BRANCH=master RTPPC_TYPE=udp
  - MM_TYPE=opensips MM_BRANCH=master MM_REV=ad60d1f7cdacce45d70f907a4043ea41f55271c6 RTPP_BRANCH=master RTPPC_TYPE=udp
