# force run: 48
dist: bionic
language: python
python:
  - "2.7"
#  - "3.3"
#  - "3.4"
#  - "3.5"
  - "3.6"
before_install:
  - echo "+++ hosts orig +++"
  - cat /etc/hosts
  - echo "--- hosts orig ---"
  - sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'
  - sudo sh -c 'echo >> /etc/hosts; grep "^127.0.0.1" /etc/hosts | sed "s|^127.0.0.1|::1|g" >> /etc/hosts'
  - echo "+++ hosts patched +++"
  - cat /etc/hosts
  - echo "--- hosts patched ---"
  - ulimit -c unlimited -S
  - sudo sh -c "echo '/tmp/core.%p.%E' > /proc/sys/kernel/core_pattern"
  - sudo -H DEBIAN_FRONTEND=noninteractive apt-get update
  - sudo -H DEBIAN_FRONTEND=noninteractive apt-get install -y gpp gdb
  - sudo pip install -r requirements.txt
  - sh -x ./install_depends/opensips.sh
script:
  - sh -x ./test_run.sh
env:
  - MM_TYPE=opensips MM_BRANCH=RFC8760 MM_AUTH=UAS/auth_db/calculate_ha1 MM_REPO=git://github.com/sippy/opensips.git RTPP_BRANCH=master RTPPC_TYPE=udp
  - MM_TYPE=opensips MM_BRANCH=RFC8760 MM_AUTH=UAS/auth_db/calculate_ha1 MM_REPO=git://github.com/sippy/opensips.git RTPP_BRANCH=master RTPPC_TYPE=udp6
  - MM_TYPE=opensips MM_BRANCH=RFC8760 MM_AUTH=UAS/auth_db/calculate_ha1 MM_REPO=git://github.com/sippy/opensips.git RTPP_BRANCH=master RTPPC_TYPE=unix
jobs:
  include:
    - name: "Build RFC8760/UAS/auth_db/calculate_ha1 @ Ubuntu 16"
      dist: xenial
      env:
        - MM_TYPE=opensips MM_BRANCH=RFC8760 MM_AUTH=UAS/auth_db/calculate_ha1 MM_REPO=git://github.com/sippy/opensips.git RTPP_BRANCH=master RTPPC_TYPE=unix
