# force run: 44
dist: xenial
language: python
python:
  - "2.7"
#  - "3.3"
#  - "3.4"
#  - "3.5"
  - "3.6"
before_install:
  - echo "+++ hosts orig +++"
  - cat /etc/hosts
  - echo "--- hosts orig ---"
  - sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'
  - sudo sh -c 'echo >> /etc/hosts; grep "^127.0.0.1" /etc/hosts | sed "s|^127.0.0.1|::1|g" >> /etc/hosts'
  - echo "+++ hosts patched +++"
  - cat /etc/hosts
  - echo "--- hosts patched ---"
  - sudo -H DEBIAN_FRONTEND=noninteractive apt-get update
  - sudo -H DEBIAN_FRONTEND=noninteractive apt-get install gpp
  - sudo pip install -r requirements.txt
  - sh -x ./install_depends/opensips.sh
script:
    sh -x ./test_run.sh
env:
## 1. Tests with Sippy B2BUA
#  - MM_TYPE=b2bua MM_BRANCH=RFC8760 RTPP_BRANCH=master RTPPC_TYPE=udp
#  - MM_TYPE=b2bua MM_BRANCH=RFC8760 RTPP_BRANCH=master RTPPC_TYPE=udp6
#  - MM_TYPE=b2bua MM_BRANCH=RFC8760 RTPP_BRANCH=master RTPPC_TYPE=unix
#  - MM_TYPE=b2bua MM_BRANCH=RFC8760 RTPP_BRANCH=master RTPPC_TYPE=cunix
#  - MM_TYPE=b2bua MM_BRANCH=RFC8760 RTPP_BRANCH=master RTPPC_TYPE=tcp
#  - MM_TYPE=b2bua MM_BRANCH=RFC8760 RTPP_BRANCH=master RTPPC_TYPE=tcp6
## 2. Tests with OpenSIPS
  - MM_TYPE=opensips MM_BRANCH=master RTPP_BRANCH=master RTPPC_TYPE=udp
  - MM_TYPE=opensips MM_BRANCH=master RTPP_BRANCH=master RTPPC_TYPE=udp6
  - MM_TYPE=opensips MM_BRANCH=master RTPP_BRANCH=master RTPPC_TYPE=unix
